ce103_hw4_test.ce103_hw4_testBase Class Reference
Public Member Functions
void ce103_strcat_cs_cs_test1 ()
override void ce103_strrev_cs_vs_cscs_test3 ()
Member Function Documentation
ce103_strcat_cs_cs_test1()
void ce103_hw4_test.ce103_hw4_testBase.ce103_strcat_cs_cs_test1 () [inline]
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcat_cs_cs().
ce103_strrev_cs_vs_cscs_test3()
override void ce103_hw4_test.ce103_hw4_testBase.ce103_strrev_cs_vs_cscs_test3 () [inline], [virtual]
Implements ce103_hw4_test.ce103_hw4_testBaseBase.
References ce103_hw4_cs_dll.ce103func.ce103_strrev_cs(), and ce103_hw4_cs_dll.ce103CsFunctions.ce103_strrev_cs_cs().
The documentation for this class was generated from the following file:
C:/Software/a/CE103-HW4-Fahrettin-Solak/ce103-hw4-test/ce103_hw4_testBase.cs